### PR TITLE
Check if master contains PR-less commit and correct exit codes

### PR DESCRIPTION
**Pull request by Apokalip**
Adding Checks for generator to check if PR-less commit is in master(should not be) and correct exit codes; Fix on string parsing from config file fixed too

Signed-off-by: Apokalip <simeon@manta.network>

### CODE REVIEW

**Review by Garandor — CHANGES_REQUESTED** [review]
1. Use `git fetch && git log origin/prev_release..origin/manta --oneline` instead of changing local branches to get the master commits
2. one more nit: trailing space after PR title when theres no [CADO] suffix on it
3. Somehow the [Added] section is missing from the generated Changelog for `release-v3.4.0`

**Comment by Apokalip** [comment]
> 1. Use `git fetch && git log origin/prev_release..origin/manta --oneline` instead of changing local branches to get the master commits
> 2. one more nit: trailing space after PR title when theres no [CADO] suffix on it
> 3. Somehow the [Added] section is missing from the generated Changelog for `release-v3.4.0`

git fetch && git log origin/prev_release..origin/manta --oneline This does not isolate manta commits, the git log is still like its called from the scope of the release

**Comment by Apokalip** [comment]
> 1. Use `git fetch && git log origin/prev_release..origin/manta --oneline` instead of changing local branches to get the master commits

@Garandor  This should probably be changed everywhere, on every git log parsing

**Comment by Garandor** [comment]
> git fetch && git log origin/prev_release..origin/manta --oneline This does not isolate manta commits, the git log is still like its called from the scope of the release

Are you sure? For me it shows
image

**Comment by Garandor** [comment]
image
it was creating trailing whitespace. fixed it. @Apokalip pls `git pull` before you continue on this

**Comment by Apokalip** [comment]
> > git fetch && git log origin/prev_release..origin/manta --oneline This does not isolate manta commits, the git log is still like its called from the scope of the release
> 
> Are you sure? For me it shows image

nope you are right, I forgot to comment out the old git log function and it was overwriting my result 😅

**Review by ghzlatarev — DISMISSED** [review]

**Comment by Apokalip** [comment]
> > git fetch && git log origin/prev_release..origin/manta --oneline This does not isolate manta commits, the git log is still like its called from the scope of the release
> 
> Are you sure? For me it shows image

Added it with 2 different commands as process::command really does not like "&&" and breaks git commands fully
Works the same way now not relying on checking out

**Review by Garandor — APPROVED** [review]
fixed git fetch origin as it needs a remote, not a branch.

LGTM!

**Review by ghzlatarev — APPROVED** [review]

**Pull request merged**
